/**
 * السيرة الذاتية الذكية - SERS
 * إنشاء سيرة ذاتية احترافية للمعلم/الإداري
 * مع 4 قوالب ATS متعددة + تعبئة AI + معاينة حية + تصدير PDF
 */
import { useState, useCallback, useMemo, useRef } from "react";
import { useLocation } from "wouter";
import {
  ArrowLeft, User, Plus, Trash2, Save, Edit3,
  Briefcase, GraduationCap, Award, Phone, Mail, MapPin,
  Star, BookOpen, Sparkles, Loader2, Eye, Printer,
  FileDown, Maximize2, Minimize2, ChevronLeft, ZoomIn, ZoomOut, RotateCcw,
  Layout, Columns, FileText, AlignJustify, Check, Languages, Crown
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import TemplateSelector, { THEMES, type ThemeConfig } from "@/components/TemplateSelector";
import { exportToPDF, printElement } from "@/lib/pdf-export";
import { usePreviewScale } from "@/hooks/usePreviewScale";
import { useEffect } from "react";

const A4_WIDTH_PX = 793.7;

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

interface CVEntry {
  id: string;
  title: string;
  organization: string;
  period: string;
  description: string;
}

interface CVData {
  name: string;
  title: string;
  phone: string;
  email: string;
  city: string;
  summary: string;
  experience: CVEntry[];
  education: CVEntry[];
  skills: string[];
  courses: CVEntry[];
  achievements: string[];
}

const STORAGE_KEY = "sers-cv-data";
function loadCV(): CVData {
  try { const s = localStorage.getItem(STORAGE_KEY); if (s) return JSON.parse(s); } catch { }
  return { name: "", title: "", phone: "", email: "", city: "", summary: "", experience: [], education: [], skills: [], courses: [], achievements: [] };
}
function saveCV(data: CVData) { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function genId() { return Date.now().toString(36) + Math.random().toString(36).slice(2, 6); }

// ═══════════════════════════════════════════════════════════════
// Language Labels
// ═══════════════════════════════════════════════════════════════

type CVLang = 'ar' | 'en';

const LABELS: Record<string, Record<CVLang, string>> = {
  summary: { ar: 'الملخص المهني', en: 'Professional Summary' },
  experience: { ar: 'الخبرات العملية', en: 'Work Experience' },
  education: { ar: 'المؤهلات العلمية', en: 'Education' },
  skills: { ar: 'المهارات', en: 'Skills' },
  courses: { ar: 'الدورات التدريبية', en: 'Training & Courses' },
  achievements: { ar: 'الإنجازات والجوائز', en: 'Awards & Achievements' },
  contact: { ar: 'معلومات الاتصال', en: 'Contact Information' },
  phone: { ar: 'هاتف', en: 'Phone' },
  email: { ar: 'بريد', en: 'Email' },
  location: { ar: 'الموقع', en: 'Location' },
  fullName: { ar: 'الاسم الكامل', en: 'Full Name' },
  jobTitle: { ar: 'المسمى الوظيفي', en: 'Job Title' },
  footer: { ar: 'تم إنشاؤه بواسطة منصة SERS', en: 'Generated by SERS Platform' },
  empty: { ar: 'ابدأ بتعبئة بياناتك لعرض المعاينة', en: 'Fill in your data to see the preview' },
};
function L(key: string, lang: CVLang) { return LABELS[key]?.[lang] || key; }

// ═══════════════════════════════════════════════════════════════
// CV Layout Templates
// ═══════════════════════════════════════════════════════════════

type CVLayout = "classic" | "two-column" | "professional" | "minimal" | "platinum";

const CV_LAYOUTS = [
  { id: "classic" as CVLayout, name: "كلاسيكي", desc: "عمود واحد - متوافق ATS", icon: FileText },
  { id: "two-column" as CVLayout, name: "عمودين", desc: "شريط جانبي + محتوى", icon: Columns },
  { id: "professional" as CVLayout, name: "احترافي", desc: "شريط ملون + جدول زمني", icon: Layout },
  { id: "minimal" as CVLayout, name: "بسيط أكاديمي", desc: "نظيف للبيئة الأكاديمية", icon: AlignJustify },
  { id: "platinum" as CVLayout, name: "بلاتينيوم", desc: "تصميم فاخر ATS Premium", icon: Crown },
];

// ═══════════════════════════════════════════════════════════════
// Shared section render helpers
// ═══════════════════════════════════════════════════════════════

function formatDate(periodStr: string, lang: CVLang) {
  if (!periodStr) return '';
  const parts = periodStr.split(/\s*-\s*/);
  return parts.map(p => {
    if (/^\d{4}-\d{2}$/.test(p)) {
      try {
        const date = new Date(p + '-01');
        return new Intl.DateTimeFormat(lang === 'ar' ? 'ar-SA' : 'en-US', { year: 'numeric', month: 'short' }).format(date);
      } catch { }
    }
    if (p.toLowerCase() === 'present' || p === 'الآن') return lang === 'ar' ? 'الآن' : 'Present';
    return p;
  }).join(lang === 'ar' ? ' - ' : ' - ');
}

function SectionTitle({ title, theme, fontFamily, variant = 'bordered', lang = 'ar' }: { title: string; theme: ThemeConfig; fontFamily: string; variant?: 'bordered' | 'dot' | 'plain' | 'platinum'; lang?: CVLang }) {
  const ff = lang === 'en' ? `'Inter', '${fontFamily}', sans-serif` : `'Tajawal', '${fontFamily}', sans-serif`;
  const avoidBreak = { breakInside: 'avoid' as const, pageBreakInside: 'avoid' as const };
  if (variant === 'platinum') {
    return (
      <h2 style={{ fontSize: '12px', fontWeight: '800', color: theme.primaryColor, marginBottom: '10px', paddingBottom: '6px', borderBottom: `2px solid ${theme.primaryColor}`, fontFamily: ff, textTransform: 'uppercase', letterSpacing: '1.5px', ...avoidBreak }}>
        {title}
      </h2>
    );
  }
  if (variant === 'dot') {
    return (
      <h2 style={{ fontSize: '15px', fontWeight: '700', color: theme.primaryColor, marginBottom: '12px', fontFamily: ff, display: 'flex', alignItems: 'center', gap: '8px', ...avoidBreak }}>
        <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: theme.primaryColor, display: 'inline-block' }} />
        {title}
      </h2>
    );
  }
  if (variant === 'plain') {
    return (
      <h2 style={{ fontSize: '13px', fontWeight: '700', color: '#1f2937', marginBottom: '10px', paddingBottom: '4px', borderBottom: '1px solid #e5e7eb', fontFamily: ff, textTransform: 'uppercase', letterSpacing: '0.5px', ...avoidBreak }}>
        {title}
      </h2>
    );
  }
  return (
    <h2 style={{ fontSize: '15px', fontWeight: '700', color: theme.primaryColor, marginBottom: '12px', paddingBottom: '6px', borderBottom: `2px solid ${theme.borderColor}`, fontFamily: ff, ...avoidBreak }}>
      {title}
    </h2>
  );
}

function ContactLine({ icon, text, lang = 'ar' }: { icon: string; text: string; lang?: CVLang }) {
  return <span>{icon}: {text}</span>;
}

function ExperienceList({ items, theme, withTimeline = false, lang = 'ar' }: { items: CVEntry[]; theme: ThemeConfig; withTimeline?: boolean; lang?: CVLang }) {
  const isRtl = lang === 'ar';
  const borderSide = isRtl ? 'borderRight' : 'borderLeft';
  const paddingSide = isRtl ? 'paddingRight' : 'paddingLeft';
  const dotSide = isRtl ? { right: '-7px' } : { left: '-7px' };
  return (
    <>
      {items.map((e) => (
        <div key={e.id} style={{ marginBottom: '14px', [paddingSide]: withTimeline ? '16px' : '12px', [borderSide]: withTimeline ? `3px solid ${theme.primaryColor}` : `3px solid ${theme.primaryColor}30`, position: 'relative' }}>
          {withTimeline && <div style={{ position: 'absolute', ...dotSide, top: '4px', width: '10px', height: '10px', borderRadius: '50%', background: theme.primaryColor, border: '2px solid #fff' }} />}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
            <h3 style={{ fontSize: '13px', fontWeight: '700', color: '#1f2937', margin: 0 }}>{e.title}</h3>
            <span style={{ fontSize: '10px', color: '#9ca3af', whiteSpace: 'nowrap' }}>{formatDate(e.period, lang)}</span>
          </div>
          <p style={{ fontSize: '11px', color: theme.primaryColor, margin: '2px 0 4px', fontWeight: '600' }}>{e.organization}</p>
          {e.description && <p style={{ fontSize: '11px', lineHeight: '1.8', color: '#6b7280', margin: 0, overflowWrap: 'break-word', wordBreak: 'break-word' }}>{e.description}</p>}
        </div>
      ))}
    </>
  );
}

function SkillTags({ skills, theme }: { skills: string[]; theme: ThemeConfig }) {
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
      {skills.filter(Boolean).map((s, i) => (
        <span key={i} style={{ padding: '3px 10px', borderRadius: '20px', fontSize: '10px', fontWeight: '600', backgroundColor: theme.primaryColor + '12', color: theme.primaryColor, border: `1px solid ${theme.primaryColor}25` }}>
          {s}
        </span>
      ))}
    </div>
  );
}

function SkillBars({ skills, theme }: { skills: string[]; theme: ThemeConfig }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
      {skills.filter(Boolean).map((s, i) => (
        <div key={i}>
          <div style={{ fontSize: '10px', fontWeight: '600', color: '#374151', marginBottom: '3px' }}>{s}</div>
          <div style={{ height: '4px', borderRadius: '2px', background: '#e5e7eb' }}>
            <div style={{ height: '100%', borderRadius: '2px', background: theme.primaryColor, width: `${85 - (i * 8) % 30}%` }} />
          </div>
        </div>
      ))}
    </div>
  );
}

function EmptyState({ lang = 'ar' }: { lang?: CVLang }) {
  return (
    <div style={{ textAlign: 'center', padding: '60px 0', color: '#9ca3af' }}>
      <p style={{ fontSize: '14px' }}>{L('empty', lang)}</p>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// CV Preview - Layout Router
// ═══════════════════════════════════════════════════════════════

function CVPreview({ data, theme, fontFamily, layout = 'classic', lang = 'ar' }: { data: CVData; theme: ThemeConfig; fontFamily: string; layout?: CVLayout; lang?: CVLang }) {
  const hasContent = data.name || data.title || data.summary || data.experience.length > 0 || data.education.length > 0 || data.skills.filter(Boolean).length > 0 || data.courses.length > 0 || data.achievements.filter(Boolean).length > 0;
  const isRtl = lang === 'ar';
  const dir = isRtl ? 'rtl' : 'ltr';
  const ff = isRtl ? `'${fontFamily}', sans-serif` : `'Inter', '${fontFamily}', sans-serif`;
  const headingFont = isRtl ? `'Tajawal', '${fontFamily}', sans-serif` : `'Inter', '${fontFamily}', sans-serif`;
  const base = { width: '210mm' as const, minHeight: '297mm' as const, fontFamily: ff, direction: dir as any };
  const dateStr = new Date().toLocaleDateString(isRtl ? 'ar-SA' : 'en-US');
  const marginSide = isRtl ? 'marginRight' : 'marginLeft';
  const borderAccentSide = isRtl ? 'borderRight' : 'borderLeft';

  // Contact info helper (ATS-safe: no emojis)
  const phoneLabel = `${L('phone', lang)}: ${data.phone}`;
  const emailLabel = `${L('email', lang)}: ${data.email}`;
  const locLabel = `${L('location', lang)}: ${data.city}`;
  const nameOrPlaceholder = data.name || L('fullName', lang);
  const titleOrPlaceholder = data.title || L('jobTitle', lang);

  // ═══ Layout 1: Classic (ATS-friendly single column) ═══
  if (layout === 'classic') {
    return (
      <div data-cv-content style={{ ...base, background: '#fff' }}>
        <div className="cv-main-header" style={{ background: `linear-gradient(135deg, ${theme.primaryColor}, ${theme.secondaryColor})`, color: theme.headerText, padding: '32px', display: 'flex', alignItems: 'center', gap: '24px' }}>
          <div style={{ width: '80px', height: '80px', borderRadius: '50%', backgroundColor: 'rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" />
            </svg>
          </div>
          <div style={{ flex: 1 }}>
            <h1 style={{ fontSize: '26px', fontWeight: '800', margin: '0 0 4px', fontFamily: headingFont }}>{nameOrPlaceholder}</h1>
            <p style={{ fontSize: '14px', opacity: 0.9, margin: '0 0 8px' }}>{titleOrPlaceholder}</p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', fontSize: '11px', opacity: 0.8 }}>
              {data.phone && <span>{phoneLabel}</span>}
              {data.email && <span>{emailLabel}</span>}
              {data.city && <span>{locLabel}</span>}
            </div>
          </div>
        </div>
        <div style={{ padding: '24px 32px', flex: 1 }}>
          {data.summary && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('summary', lang)} theme={theme} fontFamily={fontFamily} lang={lang} /><p style={{ fontSize: '12px', lineHeight: '2', color: '#374151', whiteSpace: 'pre-wrap' }}>{data.summary}</p></div>}
          {data.experience.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('experience', lang)} theme={theme} fontFamily={fontFamily} lang={lang} /><ExperienceList items={data.experience} theme={theme} lang={lang} /></div>}
          {data.education.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('education', lang)} theme={theme} fontFamily={fontFamily} lang={lang} /><ExperienceList items={data.education} theme={theme} lang={lang} /></div>}
          {data.skills.filter(Boolean).length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('skills', lang)} theme={theme} fontFamily={fontFamily} lang={lang} /><SkillTags skills={data.skills} theme={theme} /></div>}
          {data.courses.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('courses', lang)} theme={theme} fontFamily={fontFamily} lang={lang} />{data.courses.map(c => <div key={c.id} style={{ marginBottom: '8px', display: 'flex', justifyContent: 'space-between' }}><div><span style={{ fontSize: '12px', fontWeight: '600', color: '#1f2937' }}>{c.title}</span><span style={{ fontSize: '11px', color: '#6b7280', [marginSide]: '8px' }}>- {c.organization}</span></div><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(c.period, lang)}</span></div>)}</div>}
          {data.achievements.filter(Boolean).length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('achievements', lang)} theme={theme} fontFamily={fontFamily} lang={lang} />{data.achievements.filter(Boolean).map((a, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}><span style={{ fontSize: '11px', color: theme.primaryColor, fontWeight: '700' }}>★</span><span style={{ fontSize: '12px', color: '#374151' }}>{a}</span></div>)}</div>}
          {!hasContent && <EmptyState lang={lang} />}
        </div>
        <div className="cv-footer" style={{ borderTop: `2px solid ${theme.borderColor}`, padding: '12px 32px', display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#9ca3af', background: '#fff' }}>
          <span>{L('footer', lang)}</span><span>{dateStr}</span>
        </div>
      </div>
    );
  }

  // ═══ Layout 2: Two-Column (sidebar + main) ═══
  if (layout === 'two-column') {
    // Generate a background gradient that creates a solid 35% sidebar and 65% main area, extending across all pages
    const gradientRtl = `linear-gradient(to left, ${theme.primaryColor} 0%, ${theme.primaryColor} 35%, #ffffff 35%, #ffffff 100%)`;
    const gradientLtr = `linear-gradient(to right, ${theme.primaryColor} 0%, ${theme.primaryColor} 35%, #ffffff 35%, #ffffff 100%)`;
    const bgGradient = isRtl ? gradientRtl : gradientLtr;

    return (
      <div data-cv-content style={{ ...base, background: bgGradient, position: 'relative', display: 'flex' }}>
        {/* Sidebar Container (35%) */}
        <div style={{ width: '35%', color: '#fff', padding: '32px 20px', flexShrink: 0 }}>
          <div style={{ width: '90px', height: '90px', borderRadius: '50%', backgroundColor: 'rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto', marginBottom: '24px' }}>
            <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" /></svg>
          </div>
          <div className="cv-main-header" style={{ textAlign: 'center', marginBottom: '24px' }}>
            <h1 style={{ fontSize: '22px', fontWeight: '800', margin: '0 0 4px', fontFamily: headingFont }}>{nameOrPlaceholder}</h1>
            <p style={{ fontSize: '13px', opacity: 0.85, margin: 0 }}>{titleOrPlaceholder}</p>
          </div>
          <div style={{ marginBottom: '24px' }}>
            <h3 style={{ fontSize: '12px', fontWeight: '700', marginBottom: '10px', paddingBottom: '4px', borderBottom: '1px solid rgba(255,255,255,0.3)' }}>{L('contact', lang)}</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '11px' }}>
              {data.phone && <div>{phoneLabel}</div>}
              {data.email && <div>{emailLabel}</div>}
              {data.city && <div>{locLabel}</div>}
            </div>
          </div>
          {data.skills.filter(Boolean).length > 0 && (
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '12px', fontWeight: '700', marginBottom: '10px', paddingBottom: '4px', borderBottom: '1px solid rgba(255,255,255,0.3)' }}>{L('skills', lang)}</h3>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>
                {data.skills.filter(Boolean).map((s, i) => <span key={i} style={{ padding: '3px 8px', borderRadius: '12px', fontSize: '10px', backgroundColor: 'rgba(255,255,255,0.15)', border: '1px solid rgba(255,255,255,0.2)' }}>{s}</span>)}
              </div>
            </div>
          )}
          {data.achievements.filter(Boolean).length > 0 && (
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '12px', fontWeight: '700', marginBottom: '10px', paddingBottom: '4px', borderBottom: '1px solid rgba(255,255,255,0.3)' }}>{L('achievements', lang)}</h3>
              {data.achievements.filter(Boolean).map((a, i) => <div key={i} style={{ fontSize: '10px', marginBottom: '4px', display: 'flex', gap: '4px' }}><span style={{ color: '#fbbf24' }}>★</span> {a}</div>)}
            </div>
          )}
        </div>

        {/* Main Content Container (65%) */}
        <div style={{ width: '65%', padding: '32px 24px', display: 'flex', flexDirection: 'column' }}>
          {data.summary && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('summary', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><p style={{ fontSize: '12px', lineHeight: '2', color: '#374151', whiteSpace: 'pre-wrap' }}>{data.summary}</p></div>}
          {data.experience.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('experience', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><ExperienceList items={data.experience} theme={theme} lang={lang} /></div>}
          {data.education.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('education', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><ExperienceList items={data.education} theme={theme} lang={lang} /></div>}
          {data.courses.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('courses', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} />{data.courses.map(c => <div key={c.id} style={{ marginBottom: '8px', display: 'flex', justifyContent: 'space-between' }}><div><span style={{ fontSize: '12px', fontWeight: '600', color: '#1f2937' }}>{c.title}</span><span style={{ fontSize: '11px', color: '#6b7280', [marginSide]: '8px' }}>- {c.organization}</span></div><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(c.period, lang)}</span></div>)}</div>}
          {!hasContent && <EmptyState lang={lang} />}

          <div className="cv-footer" style={{ borderTop: `1px solid ${theme.borderColor}`, padding: '12px 0 0', display: 'flex', justifyContent: 'space-between', fontSize: '9px', color: '#9ca3af', background: 'transparent' }}>
            <span>{L('footer', lang)}</span><span>{dateStr}</span>
          </div>
        </div>
      </div>
    );
  }

  // ═══ Layout 3: Professional (accent stripe + timeline) ═══
  if (layout === 'professional') {
    return (
      <div data-cv-content style={{ ...base, background: '#fff' }}>
        <div style={{ height: '6px', background: `linear-gradient(${isRtl ? 'to left' : 'to right'}, ${theme.primaryColor}, ${theme.secondaryColor})` }} />
        <div className="cv-main-header" style={{ padding: '28px 36px 0' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '20px' }}>
            <div>
              <h1 style={{ fontSize: '28px', fontWeight: '800', color: '#1f2937', margin: '0 0 4px', fontFamily: headingFont }}>{nameOrPlaceholder}</h1>
              <p style={{ fontSize: '15px', color: theme.primaryColor, fontWeight: '600', margin: '0 0 8px' }}>{titleOrPlaceholder}</p>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', fontSize: '11px', color: '#6b7280' }}>
              {data.phone && <span>{phoneLabel}</span>}
              {data.email && <span>{emailLabel}</span>}
              {data.city && <span>{locLabel}</span>}
            </div>
          </div>
          <div style={{ height: '2px', background: `linear-gradient(${isRtl ? 'to left' : 'to right'}, ${theme.primaryColor}20, ${theme.primaryColor}, ${theme.primaryColor}20)`, marginBottom: '24px' }} />
        </div>
        <div style={{ padding: '0 36px 24px', flex: 1 }}>
          {data.summary && <div style={{ marginBottom: '24px', padding: '16px', background: `${theme.primaryColor}08`, borderRadius: '8px', [borderAccentSide]: `4px solid ${theme.primaryColor}` }}><p style={{ fontSize: '12px', lineHeight: '2', color: '#374151', whiteSpace: 'pre-wrap', margin: 0 }}>{data.summary}</p></div>}
          {data.experience.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('experience', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><ExperienceList items={data.experience} theme={theme} withTimeline lang={lang} /></div>}
          {data.education.length > 0 && <div style={{ marginBottom: '24px' }}><SectionTitle title={L('education', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><ExperienceList items={data.education} theme={theme} withTimeline lang={lang} /></div>}
          <div style={{ display: 'flex', gap: '24px' }}>
            {data.skills.filter(Boolean).length > 0 && <div style={{ flex: 1 }}><SectionTitle title={L('skills', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} /><SkillTags skills={data.skills} theme={theme} /></div>}
            {data.achievements.filter(Boolean).length > 0 && <div style={{ flex: 1 }}><SectionTitle title={L('achievements', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} />{data.achievements.filter(Boolean).map((a, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '5px' }}><span style={{ color: theme.primaryColor, fontSize: '12px', fontWeight: '700' }}>★</span><span style={{ fontSize: '11px', color: '#374151' }}>{a}</span></div>)}</div>}
          </div>
          {data.courses.length > 0 && <div style={{ marginTop: '24px' }}><SectionTitle title={L('courses', lang)} theme={theme} fontFamily={fontFamily} variant="dot" lang={lang} />{data.courses.map(c => <div key={c.id} style={{ marginBottom: '6px', display: 'flex', justifyContent: 'space-between' }}><div><span style={{ fontSize: '11px', fontWeight: '600', color: '#1f2937' }}>{c.title}</span><span style={{ fontSize: '10px', color: '#6b7280', [marginSide]: '6px' }}>- {c.organization}</span></div><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(c.period, lang)}</span></div>)}</div>}
          {!hasContent && <EmptyState lang={lang} />}
        </div>
        <div className="cv-footer" style={{ borderTop: `2px solid ${theme.borderColor}`, padding: '10px 36px', display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#9ca3af', background: '#fff' }}>
          <span>{L('footer', lang)}</span><span>{dateStr}</span>
        </div>
      </div>
    );
  }

  // ═══ Layout 5: Platinum (Premium ATS - resumedone style) ═══
  if (layout === 'platinum') {
    return (
      <div data-cv-content style={{ ...base, background: '#fff' }}>
        {/* Thin top accent */}
        <div style={{ height: '4px', background: theme.primaryColor }} />
        {/* Header */}
        <div className="cv-main-header" style={{ padding: '32px 36px 20px' }}>
          <h1 style={{ fontSize: '30px', fontWeight: '800', color: '#111827', margin: '0 0 4px', fontFamily: headingFont, letterSpacing: '-0.5px' }}>{nameOrPlaceholder}</h1>
          <p style={{ fontSize: '15px', color: theme.primaryColor, fontWeight: '600', margin: '0 0 12px', letterSpacing: '0.5px' }}>{titleOrPlaceholder}</p>
          {/* Contact pills */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', fontSize: '10px' }}>
            {data.phone && <span style={{ padding: '4px 12px', borderRadius: '20px', background: '#f3f4f6', color: '#374151', fontWeight: '500' }}>{phoneLabel}</span>}
            {data.email && <span style={{ padding: '4px 12px', borderRadius: '20px', background: '#f3f4f6', color: '#374151', fontWeight: '500' }}>{emailLabel}</span>}
            {data.city && <span style={{ padding: '4px 12px', borderRadius: '20px', background: '#f3f4f6', color: '#374151', fontWeight: '500' }}>{locLabel}</span>}
          </div>
          <div style={{ height: '1px', background: '#e5e7eb', marginTop: '20px' }} />
        </div>
        {/* Two-column body via flex */}
        {/* Using standard flex column for the wrapper, and letting the inner content dictate height */}
        <div style={{ display: 'flex', padding: '0 36px 24px', gap: '28px', flex: 1 }}>
          {/* Main column (65%) */}
          <div style={{ flex: '0 0 62%', display: 'flex', flexDirection: 'column' }}>
            {data.summary && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('summary', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} /><p style={{ fontSize: '11.5px', lineHeight: '1.9', color: '#374151', whiteSpace: 'pre-wrap', margin: 0, [borderAccentSide]: `3px solid ${theme.primaryColor}20`, padding: isRtl ? '0 12px 0 0' : '0 0 0 12px' }}>{data.summary}</p></div>}
            {data.experience.length > 0 && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('experience', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} /><ExperienceList items={data.experience} theme={theme} withTimeline lang={lang} /></div>}
            {data.education.length > 0 && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('education', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} /><ExperienceList items={data.education} theme={theme} lang={lang} /></div>}
          </div>
          {/* Sidebar column (35%) */}
          <div style={{ flex: '1', [borderAccentSide]: `1px solid #e5e7eb`, padding: isRtl ? '0 16px 0 0' : '0 0 0 16px', display: 'flex', flexDirection: 'column' }}>
            {data.skills.filter(Boolean).length > 0 && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('skills', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} /><SkillBars skills={data.skills} theme={theme} /></div>}
            {data.courses.length > 0 && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('courses', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} />{data.courses.map(c => <div key={c.id} style={{ marginBottom: '8px' }}><div style={{ fontSize: '11px', fontWeight: '600', color: '#1f2937' }}>{c.title}</div><div style={{ fontSize: '10px', color: '#6b7280' }}>{c.organization}</div><div style={{ fontSize: '9px', color: '#9ca3af' }}>{formatDate(c.period, lang)}</div></div>)}</div>}
            {data.achievements.filter(Boolean).length > 0 && <div style={{ marginBottom: '22px' }}><SectionTitle title={L('achievements', lang)} theme={theme} fontFamily={fontFamily} variant="platinum" lang={lang} />{data.achievements.filter(Boolean).map((a, i) => <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '6px', marginBottom: '6px' }}><span style={{ color: theme.primaryColor, fontSize: '10px', fontWeight: '800', flexShrink: 0, marginTop: '1px' }}>★</span><span style={{ fontSize: '10px', color: '#374151', lineHeight: '1.6' }}>{a}</span></div>)}</div>}
          </div>
        </div>

        {/* Footer */}
        <div className="cv-footer" style={{ borderTop: '1px solid #e5e7eb', margin: '0 36px', padding: '10px 0', display: 'flex', justifyContent: 'space-between', fontSize: '9px', color: '#9ca3af', marginTop: 'auto' }}>
          <span>{L('footer', lang)}</span><span>{dateStr}</span>
        </div>
      </div>
    );
  }

  // ═══ Layout 4: Minimal Academic ═══
  return (
    <div data-cv-content style={{ ...base, background: '#fff', padding: '40px 36px 80px' }}>
      <div className="cv-main-header" style={{ textAlign: 'center', marginBottom: '24px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#1f2937', margin: '0 0 4px', fontFamily: headingFont }}>{nameOrPlaceholder}</h1>
        <p style={{ fontSize: '14px', color: '#6b7280', margin: '0 0 8px' }}>{titleOrPlaceholder}</p>
        <div style={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap', gap: '16px', fontSize: '11px', color: '#9ca3af' }}>
          {data.phone && <span>{data.phone}</span>}
          {data.email && <span>{data.email}</span>}
          {data.city && <span>{data.city}</span>}
        </div>
        <div style={{ width: '60px', height: '1px', background: '#d1d5db', margin: '16px auto 0' }} />
      </div>
      {data.summary && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('summary', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} /><p style={{ fontSize: '12px', lineHeight: '2', color: '#374151', whiteSpace: 'pre-wrap' }}>{data.summary}</p></div>}
      {data.experience.length > 0 && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('experience', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} />{data.experience.map(e => <div key={e.id} style={{ marginBottom: '12px' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong style={{ fontSize: '12px', color: '#1f2937' }}>{e.title}</strong><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(e.period, lang)}</span></div><p style={{ fontSize: '11px', color: '#6b7280', margin: '2px 0 0' }}>{e.organization}{e.description ? ` — ${e.description}` : ''}</p></div>)}</div>}
      {data.education.length > 0 && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('education', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} />{data.education.map(e => <div key={e.id} style={{ marginBottom: '8px' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong style={{ fontSize: '12px', color: '#1f2937' }}>{e.title}</strong><span style={{ fontSize: '10px', color: '#9ca3af' }}>{formatDate(e.period, lang)}</span></div><p style={{ fontSize: '11px', color: '#6b7280', margin: '2px 0 0' }}>{e.organization}</p></div>)}</div>}
      {data.skills.filter(Boolean).length > 0 && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('skills', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} /><p style={{ fontSize: '11px', color: '#374151', lineHeight: '2' }}>{data.skills.filter(Boolean).join(' • ')}</p></div>}
      {data.courses.length > 0 && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('courses', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} />{data.courses.map(c => <div key={c.id} style={{ marginBottom: '6px', fontSize: '11px' }}><strong style={{ color: '#1f2937' }}>{c.title}</strong> — <span style={{ color: '#6b7280' }}>{c.organization}</span> <span style={{ color: '#9ca3af', fontSize: '10px' }}>({formatDate(c.period, lang)})</span></div>)}</div>}
      {data.achievements.filter(Boolean).length > 0 && <div style={{ marginBottom: '20px' }}><SectionTitle title={L('achievements', lang)} theme={theme} fontFamily={fontFamily} variant="plain" lang={lang} />{data.achievements.filter(Boolean).map((a, i) => <div key={i} style={{ fontSize: '11px', color: '#374151', marginBottom: '4px' }}>• {a}</div>)}</div>}
      {!hasContent && <EmptyState lang={lang} />}
      <div className="cv-footer" style={{ borderTop: '1px solid #e5e7eb', paddingTop: '8px', display: 'flex', justifyContent: 'space-between', fontSize: '9px', color: '#9ca3af', background: '#fff' }}>
        <span>{L('footer', lang)}</span><span>{dateStr}</span>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// Main Component
// ═══════════════════════════════════════════════════════════════

export default function SmartCV() {
  const [, navigate] = useLocation();
  const [cvData, setCvData] = useState<CVData>(loadCV);
  const [activeSection, setActiveSection] = useState("personal");
  const [selectedTheme, setSelectedTheme] = useState<ThemeConfig>(THEMES[0]);
  const [selectedFont, setSelectedFont] = useState("Cairo");
  const [view, setView] = useState<"editor" | "preview">("editor");
  const [selectedLayout, setSelectedLayout] = useState<CVLayout>("classic");
  const [translating, setTranslating] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [fullscreen, setFullscreen] = useState(false);

  const detectedLang = useMemo<CVLang>(() => {
    const text = cvData.name || cvData.summary || cvData.experience[0]?.title || '';
    if (!text) return 'ar';
    const arabicRange = /[\u0600-\u06FF]/;
    return arabicRange.test(text) ? 'ar' : 'en';
  }, [cvData.name, cvData.summary, cvData.experience]);

  const targetLang = detectedLang === 'ar' ? 'en' : 'ar';
  const lastTranslationTime = useRef<number>(0);

  // Auto-save data to localStorage when it changes
  useEffect(() => {
    saveCV(cvData);
  }, [cvData]);

  const { containerRef: previewContainerRef, pageRef: previewPageRef, previewScale, wrapperWidth, wrapperHeight, zoomLevel, zoomIn, zoomOut, resetZoom, recalculate } = usePreviewScale();

  // Trigger scale recalculation when switching to preview mode to capture accurate height
  useEffect(() => {
    if (view === "preview") {
      const timers = [10, 50, 200].map(ms => setTimeout(recalculate, ms));
      return () => timers.forEach(clearTimeout);
    }
  }, [view, recalculate]);

  const generateCVMutation = trpc.genAI.generateCV.useMutation();
  const translateCVMutation = trpc.genAI.translateCV.useMutation();

  const updateField = useCallback((field: keyof CVData, value: any) => {
    setCvData((prev) => ({ ...prev, [field]: value }));
  }, []);

  const addEntry = useCallback((field: "experience" | "education" | "courses") => {
    setCvData((prev) => ({ ...prev, [field]: [...prev[field], { id: genId(), title: "", organization: "", period: "", description: "" }] }));
  }, []);

  const updateEntry = useCallback((field: "experience" | "education" | "courses", id: string, key: keyof CVEntry, value: string) => {
    setCvData((prev) => ({ ...prev, [field]: prev[field].map((e) => e.id === id ? { ...e, [key]: value } : e) }));
  }, []);

  const removeEntry = useCallback((field: "experience" | "education" | "courses", id: string) => {
    setCvData((prev) => ({ ...prev, [field]: prev[field].filter((e) => e.id !== id) }));
  }, []);

  const addSkill = useCallback(() => { setCvData((prev) => ({ ...prev, skills: [...prev.skills, ""] })); }, []);
  const updateSkill = useCallback((i: number, v: string) => { setCvData((prev) => ({ ...prev, skills: prev.skills.map((s, idx) => idx === i ? v : s) })); }, []);
  const removeSkill = useCallback((i: number) => { setCvData((prev) => ({ ...prev, skills: prev.skills.filter((_, idx) => idx !== i) })); }, []);

  const addAchievement = useCallback(() => { setCvData((prev) => ({ ...prev, achievements: [...prev.achievements, ""] })); }, []);
  const updateAchievement = useCallback((i: number, v: string) => { setCvData((prev) => ({ ...prev, achievements: prev.achievements.map((a, idx) => idx === i ? v : a) })); }, []);
  const removeAchievement = useCallback((i: number) => { setCvData((prev) => ({ ...prev, achievements: prev.achievements.filter((_, idx) => idx !== i) })); }, []);

  const handleSave = useCallback(() => { saveCV(cvData); toast.success("تم حفظ السيرة الذاتية بنجاح"); }, [cvData]);

  const handleAIFill = useCallback(async () => {
    if (!cvData.name && !cvData.title) { toast.error("أدخل الاسم والمسمى الوظيفي أولاً"); return; }
    setAiLoading(true);
    try {
      const result = await generateCVMutation.mutateAsync({
        name: cvData.name,
        jobTitle: cvData.title,
        experience: cvData.experience.map((e) => e.title).filter(Boolean).join(", ") || undefined,
        education: cvData.education.map((e) => e.title).filter(Boolean).join(", ") || undefined,
        skills: cvData.skills.filter(Boolean).join(", ") || undefined,
        language: detectedLang,
      });
      if (result.success && result.cvData) {
        const ai = result.cvData as any;
        setCvData((prev) => ({
          ...prev,
          summary: ai.summary || prev.summary,
          experience: ai.experience?.length ? ai.experience.map((e: any) => ({ id: genId(), ...e })) : prev.experience,
          education: ai.education?.length ? ai.education.map((e: any) => ({ id: genId(), ...e })) : prev.education,
          skills: ai.skills?.length ? ai.skills : prev.skills,
          courses: ai.courses?.length ? ai.courses.map((c: any) => ({ id: genId(), ...c })) : prev.courses,
          achievements: ai.achievements?.length ? ai.achievements : prev.achievements,
        }));
        toast.success(detectedLang === 'en' ? 'CV generated successfully with AI' : 'تم توليد السيرة الذاتية بالذكاء الاصطناعي');
      }
    } catch (err) { console.error(err); toast.error("حدث خطأ أثناء التوليد. الرجاء المحاولة مرة أخرى."); }
    finally { setAiLoading(false); }
  }, [cvData, detectedLang, generateCVMutation]);

  const handleTranslate = useCallback(async () => {
    const hasData = cvData.name || cvData.summary || cvData.experience.length > 0 || cvData.skills.filter(Boolean).length > 0;
    if (!hasData) {
      toast.error(detectedLang === 'ar' ? 'يرجى إضافة بيانات لترجمتها' : 'Please add data to translate');
      return;
    }

    const now = Date.now();
    if (now - lastTranslationTime.current < 2000) {
      return;
    }
    lastTranslationTime.current = now;

    setTranslating(true);
    try {
      const result = await translateCVMutation.mutateAsync({
        cvData: {
          name: cvData.name,
          title: cvData.title,
          summary: cvData.summary,
          experience: cvData.experience.map(e => ({ title: e.title, organization: e.organization, period: e.period, description: e.description })),
          education: cvData.education.map(e => ({ title: e.title, organization: e.organization, period: e.period, description: e.description })),
          skills: cvData.skills,
          courses: cvData.courses.map(c => ({ title: c.title, organization: c.organization, period: c.period, description: c.description })),
          achievements: cvData.achievements,
        },
        targetLanguage: targetLang,
      });
      if (result.success && result.translatedData) {
        const t = result.translatedData as any;
        setCvData(prev => ({
          ...prev,
          name: t.name || prev.name,
          title: t.title || prev.title,
          summary: t.summary || prev.summary,
          experience: t.experience?.length ? t.experience.map((e: any, i: number) => { const { id, ...rest } = e; return { ...prev.experience[i], ...rest, id: prev.experience[i]?.id || genId() }; }) : prev.experience,
          education: t.education?.length ? t.education.map((e: any, i: number) => { const { id, ...rest } = e; return { ...prev.education[i], ...rest, id: prev.education[i]?.id || genId() }; }) : prev.education,
          skills: t.skills?.length ? t.skills : prev.skills,
          courses: t.courses?.length ? t.courses.map((c: any, i: number) => { const { id, ...rest } = c; return { ...prev.courses[i], ...rest, id: prev.courses[i]?.id || genId() }; }) : prev.courses,
          achievements: t.achievements?.length ? t.achievements : prev.achievements,
        }));
        toast.success(targetLang === 'en' ? 'Translated to English' : 'تمت الترجمة إلى العربية');
      }
    } catch (err) { console.error(err); toast.error("حدث خطأ أثناء الترجمة الذكية. الرجاء المحاولة مرة أخرى."); }
    finally { setTranslating(false); }
  }, [cvData, detectedLang, targetLang, translateCVMutation]);

  const handleExportPDF = useCallback(async () => {
    setExporting(true);
    try { await exportToPDF("cv-preview-content", `${cvData.name || "سيرة-ذاتية"}.pdf`); toast.success("تم تصدير PDF بنجاح"); }
    catch { toast.error("حدث خطأ أثناء التصدير"); }
    finally { setExporting(false); }
  }, [cvData.name]);

  const handlePrint = useCallback(() => { try { printElement("cv-preview-content"); } catch { toast.error("حدث خطأ"); } }, []);

  const sections = [
    { id: "personal", label: "البيانات الشخصية", icon: User },
    { id: "experience", label: "الخبرات", icon: Briefcase },
    { id: "education", label: "المؤهلات", icon: GraduationCap },
    { id: "skills", label: "المهارات", icon: Star },
    { id: "courses", label: "الدورات", icon: BookOpen },
    { id: "achievements", label: "الإنجازات", icon: Award },
  ];

  return (
    <div className="min-h-screen pb-20 lg:pb-0 bg-[#F8FAFC]" dir="rtl">
      {/* Header */}
      <div className="w-full bg-gradient-to-l from-teal-700 via-teal-600 to-emerald-500">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
          <button type="button" onClick={() => navigate("/")} className="flex items-center gap-2 text-white/70 hover:text-white mb-3 transition-colors">
            <ChevronLeft className="w-4 h-4" /><span className="text-sm">العودة للرئيسية</span>
          </button>
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-white/15 backdrop-blur-sm flex items-center justify-center">
                <User className="w-7 h-7 text-white" />
              </div>
              <div>
                <h1 className="text-2xl md:text-3xl font-black text-white" style={{ fontFamily: "'Tajawal', sans-serif" }}>السيرة الذاتية الذكية</h1>
                <p className="text-white/80 text-sm mt-1">إنشاء سيرة ذاتية احترافية مع دعم الذكاء الاصطناعي</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={handleTranslate} disabled={translating}
                variant="outline" size="sm" className="gap-1.5 text-white border-white/30 hover:bg-white/10">
                {translating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Languages className="w-4 h-4" />}
                {translating ? "جاري الترجمة..." : `ترجمة إلى ${targetLang === 'en' ? 'EN' : 'عربية'}`}
              </Button>
              <Button onClick={handleAIFill} variant="outline" size="sm" disabled={aiLoading}
                className="gap-1.5 text-white border-white/30 hover:bg-white/10">
                {aiLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                {aiLoading ? "جاري التوليد..." : "تعبئة AI"}
              </Button>
              <Button onClick={handleSave} variant="outline" size="sm" className="gap-1 text-white border-white/30 hover:bg-white/10">
                <Save className="w-4 h-4" /> حفظ
              </Button>
              {view === "editor" ? (
                <Button onClick={() => setView("preview")} size="sm" className="gap-1 bg-white text-teal-800 hover:bg-gray-100">
                  <Eye className="w-4 h-4" /> معاينة وتصدير
                </Button>
              ) : (
                <Button onClick={() => { setView("editor"); setFullscreen(false); }} size="sm" className="gap-1 bg-white text-teal-800 hover:bg-gray-100">
                  <Edit3 className="w-4 h-4" /> تعديل
                </Button>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
        <>
          {/* ═══ Editor View ═══ */}
          {view === "editor" && (
            <div key="editor">
              {/* Layout Selector */}
              <div className="mb-4">
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <label className="text-xs font-semibold text-gray-700 mb-3 block flex items-center gap-1.5" style={{ fontFamily: "'Tajawal', sans-serif" }}>
                    <Layout className="w-4 h-4 text-teal-600" /> تصميم السيرة الذاتية
                  </label>
                  <div className="grid grid-cols-3 sm:grid-cols-5 gap-2">
                    {CV_LAYOUTS.map((l) => {
                      const Icon = l.icon;
                      const isActive = selectedLayout === l.id;
                      return (
                        <button key={l.id} type="button" onClick={() => { setSelectedLayout(l.id); toast.success(`تم اختيار تصميم: ${l.name}`, { duration: 1500 }); }}
                          style={{ touchAction: 'manipulation' }}
                          className={`relative flex flex-col items-center gap-1.5 p-3 sm:p-4 rounded-lg border-2 transition-all active:scale-95 ${isActive ? 'border-teal-600 bg-teal-50 shadow-sm' : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                            }`}>
                          <Icon className={`w-5 h-5 ${isActive ? 'text-teal-600' : 'text-gray-500'}`} />
                          <span className={`text-[11px] font-semibold ${isActive ? 'text-teal-700' : 'text-gray-700'}`}>{l.name}</span>
                          <span className="text-[9px] text-gray-400 leading-tight text-center">{l.desc}</span>
                          {isActive && <div className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-teal-600 rounded-full flex items-center justify-center shadow-sm"><Check className="w-3 h-3 text-white" /></div>}
                        </button>
                      );
                    })}
                  </div>
                </div>
              </div>

              {/* Theme Selector */}
              <div className="mb-4">
                <TemplateSelector selectedTheme={selectedTheme} onThemeChange={setSelectedTheme} selectedFont={selectedFont} onFontChange={setSelectedFont} compact />
              </div>

              {/* Section tabs */}
              <div className="flex flex-wrap gap-1.5 mb-4">
                {sections.map((sec) => {
                  const Icon = sec.icon;
                  return (
                    <button key={sec.id} onClick={() => setActiveSection(sec.id)}
                      className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-all ${activeSection === sec.id ? "bg-teal-700 text-white" : "bg-white text-gray-600 hover:bg-gray-50 border border-gray-200"
                        }`}>
                      <Icon className="w-3.5 h-3.5" /> {sec.label}
                    </button>
                  );
                })}
              </div>

              {/* Section content */}
              <>
                <div key={activeSection}
                  className="bg-white rounded-xl border border-gray-200 p-5">
                  {activeSection === "personal" && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="md:col-span-2">
                        <label className="block text-xs font-medium text-gray-500 mb-1">الاسم الكامل</label>
                        <input type="text" value={cvData.name} onChange={(e) => updateField("name", e.target.value)} placeholder="محمد أحمد العلي"
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20" />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-500 mb-1">المسمى الوظيفي</label>
                        <input type="text" value={cvData.title} onChange={(e) => updateField("title", e.target.value)} placeholder="معلم رياضيات"
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20" />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-500 mb-1">رقم الجوال</label>
                        <input type="text" value={cvData.phone} onChange={(e) => updateField("phone", e.target.value)} placeholder="05XXXXXXXX"
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20" />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-500 mb-1">البريد الإلكتروني</label>
                        <input type="email" value={cvData.email} onChange={(e) => updateField("email", e.target.value)} placeholder="email@example.com"
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20" />
                      </div>
                      <div>
                        <label className="block text-xs font-medium text-gray-500 mb-1">المدينة</label>
                        <input type="text" value={cvData.city} onChange={(e) => updateField("city", e.target.value)} placeholder="الرياض"
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20" />
                      </div>
                      <div className="md:col-span-2">
                        <label className="block text-xs font-medium text-gray-500 mb-1">نبذة مختصرة</label>
                        <textarea value={cvData.summary} onChange={(e) => updateField("summary", e.target.value)}
                          placeholder="نبذة مختصرة عن خبراتك وتخصصك..." rows={3}
                          className="w-full px-3 py-2.5 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-slate-500/20 resize-y" />
                      </div>
                    </div>
                  )}

                  {(activeSection === "experience" || activeSection === "education" || activeSection === "courses") && (
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-bold text-gray-800 text-sm" style={{ fontFamily: "'Tajawal', sans-serif" }}>
                          {sections.find((s) => s.id === activeSection)?.label}
                        </h3>
                        <Button onClick={() => addEntry(activeSection as any)} variant="outline" size="sm" className="gap-1">
                          <Plus className="w-3 h-3" /> إضافة
                        </Button>
                      </div>
                      <div className="space-y-3">
                        {cvData[activeSection as "experience" | "education" | "courses"].map((entry) => (
                          <div key={entry.id} className="border border-gray-100 rounded-lg p-3">
                            <div className="flex items-center justify-between mb-2">
                              <input type="text" value={entry.title} onChange={(e) => updateEntry(activeSection as any, entry.id, "title", e.target.value)}
                                placeholder="المسمى / الدرجة" className="flex-1 bg-transparent text-sm font-bold text-gray-800 focus:outline-none" />
                              <button onClick={() => removeEntry(activeSection as any, entry.id)} className="text-gray-400 hover:text-red-500"><Trash2 className="w-4 h-4" /></button>
                            </div>
                            <div className="grid grid-cols-2 gap-2">
                              <input type="text" value={entry.organization} onChange={(e) => updateEntry(activeSection as any, entry.id, "organization", e.target.value)}
                                placeholder="الجهة / المؤسسة" className="col-span-2 px-2 py-1.5 rounded-md border border-gray-200 text-xs focus:outline-none" />
                              {(() => {
                                const parts = entry.period.split(/\s*-\s*/);
                                const start = parts[0] || '';
                                const end = parts[1] || '';
                                const isPresent = end === 'الآن' || end === 'Present';
                                return (
                                  <div className="flex items-center gap-1 col-span-2 border border-gray-200 rounded-md bg-white px-2">
                                    <span className="text-[10px] text-gray-400 whitespace-nowrap">من:</span>
                                    <input type="month" value={/^\d{4}-\d{2}$/.test(start) ? start : ''} onChange={(e) => updateEntry(activeSection as any, entry.id, "period", `${e.target.value} - ${end}`)}
                                      className="flex-1 py-1 text-xs focus:outline-none bg-transparent min-w-0" />
                                    <span className="text-[10px] text-gray-400 whitespace-nowrap">إلى:</span>
                                    {!isPresent && (
                                      <input type="month" value={/^\d{4}-\d{2}$/.test(end) ? end : ''} onChange={(e) => updateEntry(activeSection as any, entry.id, "period", `${start} - ${e.target.value}`)}
                                        className="flex-1 py-1 text-xs focus:outline-none bg-transparent min-w-0" />
                                    )}
                                    <label className="flex items-center gap-1 text-[10px] text-gray-500 whitespace-nowrap shrink-0 ml-1">
                                      <input type="checkbox" checked={isPresent} onChange={(e) => updateEntry(activeSection as any, entry.id, "period", `${start} - ${e.target.checked ? 'الآن' : ''}`)} />
                                      للآن
                                    </label>
                                  </div>
                                );
                              })()}
                            </div>
                            <textarea value={entry.description} onChange={(e) => updateEntry(activeSection as any, entry.id, "description", e.target.value)}
                              placeholder="وصف مختصر..." rows={2} className="w-full mt-2 px-2 py-1.5 rounded-md border border-gray-200 text-xs focus:outline-none resize-none" />
                          </div>
                        ))}
                        {cvData[activeSection as "experience" | "education" | "courses"].length === 0 && (
                          <p className="text-center text-gray-400 text-sm py-6">لا توجد عناصر. اضغط "إضافة" للبدء.</p>
                        )}
                      </div>
                    </div>
                  )}

                  {activeSection === "skills" && (
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-bold text-gray-800 text-sm" style={{ fontFamily: "'Tajawal', sans-serif" }}>المهارات</h3>
                        <Button onClick={addSkill} variant="outline" size="sm" className="gap-1"><Plus className="w-3 h-3" /> إضافة</Button>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {cvData.skills.map((skill, i) => (
                          <div key={i} className="flex items-center gap-1 bg-gray-50 rounded-lg px-2 py-1 border border-gray-200">
                            <input type="text" value={skill} onChange={(e) => updateSkill(i, e.target.value)} placeholder="مهارة..."
                              className="bg-transparent text-xs w-28 focus:outline-none" />
                            <button onClick={() => removeSkill(i)} className="text-gray-400 hover:text-red-500"><Trash2 className="w-3 h-3" /></button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {activeSection === "achievements" && (
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="font-bold text-gray-800 text-sm" style={{ fontFamily: "'Tajawal', sans-serif" }}>الإنجازات</h3>
                        <Button onClick={addAchievement} variant="outline" size="sm" className="gap-1"><Plus className="w-3 h-3" /> إضافة</Button>
                      </div>
                      <div className="space-y-2">
                        {cvData.achievements.map((ach, i) => (
                          <div key={i} className="flex items-center gap-2">
                            <Award className="w-4 h-4 text-amber-500 shrink-0" />
                            <input type="text" value={ach} onChange={(e) => updateAchievement(i, e.target.value)} placeholder="إنجاز أو جائزة..."
                              className="flex-1 px-2 py-1.5 rounded-md border border-gray-200 text-xs focus:outline-none" />
                            <button onClick={() => removeAchievement(i)} className="text-gray-400 hover:text-red-500"><Trash2 className="w-3 h-3" /></button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </>
            </div>
          )}

          {/* ═══ Preview View ═══ */}
          {view === "preview" && (
            <div key="preview"
              className={fullscreen ? "fixed inset-0 z-50 bg-gray-100 overflow-auto" : ""}>
              <div className={`bg-white border-b border-gray-200 ${fullscreen ? "sticky top-0 z-10 shadow-sm" : "rounded-t-xl border border-gray-200"}`}>
                <div className="flex items-center justify-between px-3 sm:px-4 py-2 sm:py-3 gap-2">
                  <div className="flex items-center gap-2 sm:gap-3">
                    <button onClick={() => { setView("editor"); setFullscreen(false); }} className="text-gray-400 hover:text-gray-600"><ArrowLeft className="w-5 h-5" /></button>
                    <Eye className="w-4 h-4 text-teal-500 hidden sm:block" />
                    <span className="text-xs sm:text-sm font-semibold text-gray-800" style={{ fontFamily: "'Tajawal', sans-serif" }}>معاينة السيرة الذاتية</span>
                  </div>
                  <div className="flex items-center gap-1.5 sm:gap-2">
                    <Button size="sm" onClick={handleExportPDF} disabled={exporting} className="gap-1 sm:gap-1.5 text-xs h-8 sm:h-9 bg-teal-600 hover:bg-teal-700 text-white">
                      {exporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileDown className="w-3.5 h-3.5" />}
                      <span className="hidden sm:inline">{exporting ? 'جاري التصدير...' : 'تصدير PDF'}</span>
                      <span className="sm:hidden">PDF</span>
                    </Button>
                    <Button variant="ghost" size="sm" onClick={() => setFullscreen(!fullscreen)} className="p-1.5 h-8 sm:h-9">
                      {fullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
                    </Button>
                  </div>
                </div>
                <div className="flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 pb-2 sm:pb-3 overflow-x-auto" style={{ WebkitOverflowScrolling: 'touch', scrollbarWidth: 'none' }}>
                  <div className="flex items-center gap-0.5 bg-white/90 backdrop-blur-sm border border-gray-200 rounded-lg shadow-sm px-1 py-0.5 shrink-0">
                    <button onClick={zoomOut} className="p-1.5 hover:bg-gray-100 rounded-md transition-colors active:scale-95" title="تصغير">
                      <ZoomOut className="w-3.5 h-3.5 text-gray-600" />
                    </button>
                    <div className="px-1.5 min-w-[2.5rem] text-center">
                      <span className="text-[10px] font-mono text-gray-700 font-medium">{zoomLevel}%</span>
                    </div>
                    <button onClick={zoomIn} className="p-1.5 hover:bg-gray-100 rounded-md transition-colors active:scale-95" title="تكبير">
                      <ZoomIn className="w-3.5 h-3.5 text-gray-600" />
                    </button>
                    <div className="w-px h-4 bg-gray-200 mx-0.5" />
                    <button onClick={resetZoom} className="p-1.5 hover:bg-gray-100 rounded-md transition-colors active:scale-95" title="إعادة الحجم الأصلي">
                      <RotateCcw className="w-3 h-3 text-gray-500" />
                    </button>
                  </div>
                  <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1 text-xs h-8 shrink-0">
                    <Printer className="w-3.5 h-3.5" /><span className="hidden sm:inline">طباعة</span>
                  </Button>
                </div>
              </div>
              {/* Preview Content - A4 مضغوط بـ transform: scale() */}
              <div ref={previewContainerRef} className={`bg-gray-200 overflow-auto ${fullscreen ? "h-[calc(100vh-52px)]" : "max-h-[80vh] rounded-b-xl border-x border-b border-gray-200"}`} style={{ padding: '8px 4px', minHeight: '200px' }}>
                <div style={{ width: `${wrapperWidth}px`, height: `${wrapperHeight}px`, margin: '0 auto', position: 'relative', overflow: 'hidden' }}>
                  <div style={{ width: `${A4_WIDTH_PX}px`, transformOrigin: 'top right', transform: `scale(${previewScale})`, transition: 'transform 0.15s ease-out' }}>
                    <div id="cv-preview-content" ref={previewPageRef} style={{ fontFamily: detectedLang === 'en' ? "'Inter', sans-serif" : "'Cairo', sans-serif", direction: detectedLang === 'en' ? 'ltr' : 'rtl', width: '210mm', minHeight: '297mm', backgroundColor: 'white', position: 'relative', wordBreak: 'break-word', overflowWrap: 'break-word' }}>
                      <style dangerouslySetInnerHTML={{__html: `
                        #cv-preview-content .cv-main-header { break-inside: avoid; page-break-inside: avoid; }
                        #cv-preview-content h2 { break-inside: avoid; page-break-inside: avoid; break-after: avoid; page-break-after: avoid; }
                      `}} />

                      <CVPreview data={cvData} theme={selectedTheme} fontFamily={selectedFont} layout={selectedLayout} lang={detectedLang} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </>
      </div>
    </div>
  );
}
